### ISSUE TITLE
chrome.runtime.onConnectExternal undefined, throws error when adding listener

### ISSUE THREAD

**Issue by jketcham** [zalmoxisus/crossmessaging#3]
Hey there, love this package you've put together and the implementation you have in crossbuilder with it. I've been experimenting with it in one of my projects and for some reason don't have chrome.runtime.onConnectExternal defined in my content/background script's context, so when `onConnect` fires it comes back with an error stating that `addListener` could not be applied to the undefined `onConnectExternal`.

Because my app wouldn't ever need to listen for connections from an external extension/app, would this be something that might do better as defined in some config when declaring onConnect?

Thanks for the great package!

**Comment by zalmoxisus** [comment]
Hey,

Thanks for the feedback. We added it in #1, and could of course just add `if(chrome.runtime.onConnectExternal)` before [L36](https://github.com/zalmoxisus/crossmessaging/blob/master/src/index.js#L36), but AFAIK chrome.runtime.onConnectExternal is always available on background script. Maybe you try to invoke `onConnect` in content script? Then `chrome.runtime.onConnect` shouldn't work as well.

**Comment by jketcham** [comment]
Yep this was my bad, was trying to use onConnect in the content script instead of my background script. Whoops!
